### PR TITLE
started working on adapting updated_badges.rb for stats review

### PR DESCRIPTION
**Pull request by sckott**
related issue #2 

Explanation/questions for you @mpadge 

- Badge file names are like `102_status.svg`. Because issue numbers can be duplicated among regular ropensci review and stats review, the file names have to be changed for stats review issues.
- From the issue thread on this, sounds like for stats review we only need to look for "approved", and not "review" or "seeking" as we do for regular ropensci review. Correct?
- I haven't started changing any of the code for the json file. Do you want a different json file for stats review, or all data go into one json file?
- Do you have svg files already matching the badges you shared in https://github.com/ropensci-org/badges/issues/2 ?
- I've commented some of the code so as to explain what's going on (i generally don't love a ton of commented code, but i think makes sense since others will need to maintain this)

### CODE REVIEW

**Comment by mpadge** [comment]
@sckott first thing i should have said is that stats peer review all happens in main `ropensci/software-reveiw` repo - the `ropenscilabs` repo was just a playground. That will change -- and simplify -- this PR a fair bit. Other labels ("review", "seeking", ...) can then just be applied as for normal review, and only the final "approved" badges will change.

> Do you have svg files already matching the badges you shared in new badges for stats peer review #2 ?

Yes. They are in my local clone of this repo, but not PR'ed yet until we work out exactly how to incorporate and record versioning into this whole process.

**Comment by sckott** [comment]
@mpadge thanks for the correction on the repo location!

Okay, got it on the labels.

**Comment by sckott** [comment]
@mpadge Just pushed more changes, see commit notes above for changes. 

- do you want to be able to add color and versions info at top of script as [I just added](https://github.com/ropensci-org/badges/pull/3/files?file-filters%5B%5D=.rb#diff-b6245e1676462df450d723f0e7b9e62aefcfa5a93badf355282381e53eed4077R11-R12) or go back to adding new lines with the exact label name?
- I added a few placeholder svgs - they're not trying to be the real ones, just to be able to run code better
- still haven't touched the json file code at the bottom

let me know any comments on this

**Comment by mpadge** [comment]
@sckott One thing to note, just to ensure this has **NO** effect on the way this PR works: We had envisioned commands like `@ropensci-review-bot approve silver`, but have now changed that [as explained here](https://github.com/ropensci-org/buffy/issues/20#issuecomment-876304441) to uniform `@ropensci-review-bot approve` commands throughout, with the grades stored in a separate HTML variable held in the template header. The issue labels will nevertheless remain the same, and so all grep commands in this PR should still apply regardless, but could you just ensure everything is okay first?

I presume that you manually added the badges in the newly [created](https://github.com/ropenscilabs/statistical-software-review/issues/10) [test](https://github.com/ropenscilabs/statistical-software-review/issues/11) [issues](https://github.com/ropenscilabs/statistical-software-review/issues/12), right?

**Comment by sckott** [comment]
> I presume that you manually added the badges in the newly created test issues, right?

Yes, I did manually add them

**Comment by sckott** [comment]
The change shouldn't affect this PR since the code here is only using the labels. But I'll double check

**Comment by sckott** [comment]
The Actions workflow only runs on main branch, so we hadn't tested these changes on Actions yet, but I copied the code into a repo and it all worked as planned https://github.com/sckott/jubilant-spork/tree/gh-pages

**Comment by mpadge** [comment]
Cool, thanks. I guess the best thing to do would be to leave the merging of this PR to us, so we are symbolically taking over responsibility for the whole shebang here. It all looks great, but we'll first ensure the whole workflow from bot command through to successful generation of `onboarded.json` works seamlessly. I'm now at least vaguely confident that most of the work for that is in place, and we'll be able to take from here to get all that integrated. Thanks so much for this really helpful input!

**Comment by sckott** [comment]
> leave the merging of this PR to us

sounds good

It's been my pleasure to help!

**Pull request merged**
