### PR TITLE
label event

### PR DESCRIPTION
**Pull request by maelle**
See https://github.com/r-hub/docs/blob/master/.github/workflows/pr.yml (that works but is for PRs)

and https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues

### CODE REVIEW

**Comment by maelle** [comment]
ah but this would only work if the workflow were in the software-review repo, sorry @sckott @karthik

**Comment by maelle** [comment]
Also, you could add "unlabeled", "opened", "closed" as types I suppose.

**Comment by sckott** [comment]
i'm a bit confused, so the trigger on label would work or would not?

**Comment by maelle** [comment]
it would work (unless I forgot a tab or so) but the workflow file has to live in the repo where the issues are labelled i.e. in sotware-review.

**Comment by sckott** [comment]
ok. i think it just makes more sense to have the badges stuff be a in separate repo. maybe @karthik has a preference here

**Comment by karthik** [comment]
I have no preference here. If Maëlle is saying that it only works if the code is in the same repo as the labels, then we might have to move it to the `software review` repo.

**Comment by mpadge** [comment]
@maelle If this is not going to work anyway, can we just close now?

**Pull request closed without merging**
